### ISSUE TITLE
Images on README.md

### ISSUE THREAD

**Issue by alorma** [aeracoop/FloneRemote#13]
First, fourth and fifth images are not showing in the README section

**Comment by rocboronat** [comment]
Probably an issue with your connection? No idea, but it's working now. Please, comment this issue again if you see it again. Thanks!

**Comment by rocboronat** [comment]
Wep! Just seen the issue. Probably an issue with GitHub? Who knows. But we need to find a workaround.

**Comment by rocboronat** [comment]
Fix'd!
