### ISSUE TITLE
Button ADD not working with there is already one

### ISSUE THREAD

**Issue by lotelx** [aeracoop/FloneRemote#29]
I was unable to add new drone when there is already one on the list.
The only way is go to the app android options, delete all the cache and data of the app and then the button works again... but only for add only one, then it will not work again if there is one on the list.

I also miss a option for remove a previous drone.

**Comment by rocboronat** [comment]
@lotelx wep! It happens in the last version of the app? I cannot reproduce it...

BTW, to remove an existing Flone, do a long tap on it and you will be prompted :·)

![2015-11-27 21 54 41](https://cloud.githubusercontent.com/assets/456499/11448508/0127a416-955a-11e5-8308-d875e2fb0dcd.png)

**Comment by lotelx** [comment]
Still not working with the new version that I downloaded today. 
I can have only one device on the list.

**Comment by rocboronat** [comment]
Hi @lotelx ! We cannot reproduce it. Look at our phones:

![2016-01-08 17 20 21](https://cloud.githubusercontent.com/assets/456499/12204448/93d58b34-b634-11e5-9a8c-766e6eaaa274.png)
