### ISSUE TITLE
See controls with drone disarmed

### ISSUE THREAD

**Issue by lotelx** [aeracoop/FloneRemote#30]
The app should show the main activity even when disarmed.
Not make any sense that for test or trim or see the controls the drone should be armed! 

This means that all test should made with the drone armed ? No way!

**Comment by rocboronat** [comment]
Do you think that this can be joined with this other issue? https://github.com/Fewlaps/flone-android/issues/28

**Comment by rocboronat** [comment]
Done!

![2016-01-08 17 35 55](https://cloud.githubusercontent.com/assets/456499/12204782/bda81862-b636-11e5-9778-da36f5311113.png)
