### ISSUE TITLE
Channel not in order

### ISSUE THREAD

**Issue by lotelx** [aeracoop/FloneRemote#31]
Actually the  channels are not working well.

Throttle moves yaw, and  yaw move throttle.

The app should have the option to send the channel order in different ways (Multiwii or cleanflight) way.

**Comment by rocboronat** [comment]
WTF! Are you telling me that Multiwii and Cleanfight channels are using different channels...?

I understood that the "P" of "MultiWii Protocol" also talked about what channels are used for every case...

Hope that this fix will make my Flone flight again! :·)

**Comment by rocboronat** [comment]
Fixed!
