### ISSUE TITLE
Flone fruit (apple) harvester - precision farming MLM

### ISSUE THREAD

**Issue by ecnr** [aeracoop/FloneRemote#46]
Dear gold Flone developers,

I am contacting you because of specific open source development thread. In Vijay Kumar TEDxPenn Talk (Sikang Liu, Giuseppe Loianno, Yash Mulgaonkar, Gareth Cross) is highlighted Flone, drone with simple robotic hand and drones with software enhancement for precision farming (fruit recognition).

https://www.facebook.com/mirecek.lacoste/videos/1355933114439228/

My interest is in open source intersection - flone fruit (apple) harvester. Any workgroup relating to such flone enhancement?

Thank you for your ideas, connections and actions - pointed attention,

With best regards,

Mirek Fajx
Diamond Multi Level Marketing Dealer
LR Health & Beauty Systems / COOP GAY.CZ
http://lr.neocities.org
http://www.gay.cz

**Comment by rocboronat** [comment]
@lotelx any idea about this?

**Comment by lotelx** [comment]
Hi,
The project phlone, the spin-off from Vijay Jumar and flone.cc the flying phone, are totally different projects.
There are nobody of our group working on this application.

**Comment by ecnr** [comment]
Maybe it could be issue for future consideration -- if possibly some developers find it interesting they could gather and create development movement inside this project.
I am trying to find out if there is open source activity in this field and for now I had end up here -- hoping if such open source seed can't flourish anywhere else... maybe between people with open source minds can create better path to flourish... Talking the talk couldn't keep us back....

**Comment by ecnr** [comment]
Flone Fruit Harvester, OPEN SOURCE, LR Precision Farming MLM

Dont let yourself be scared with open mind... Just a bit of flow as starter.


Flone fruit harvester - Precision farming MLM
•	tree mapping (where are trees, where is the fruit)
•	autonomous exploration & mapping -- https://github.com/crmaykish/mercator
•	object recognition, fruit recognition -- https://github.com/zhacarias/Fruit-Recognition   --  https://github.com/meikunding/Fruit-Recognition-and-Location

![screenshot_2016-11-30-12-12-35](https://cloud.githubusercontent.com/assets/24223167/20758535/6a8bedbc-b71a-11e6-9164-23a9b553f8e7.png)


•	fruit to robotic gripper/hand position (move to harvesting position)
•	fruit harvesting, object harvesting
•	fly automation, flight plan based on tree maping and object recognition -- https://github.com/IRakhman/QuadcopterNavigation
•	fly positioning to object
•	catching object-clap, robotic gripper/hand (for apples and most others 2 kitchen like ladles should serve well)   -- https://github.com/search?utf8=✓&q=gripper&type=Repositories&ref=searchresults
•	drop to box (release fruit)
•	processing speed tunning

Git Modules/Libraries 
•	Flone

Git connections based on interest
•	Fruit harvester
•	Object recognition
•	Flight planning/automation

Fruit types scope (robotic gripper/hand modifications)
•	Apple
•	Pear
•	Orange
•	Mandarine
•	Plum / Blum / "Ringle"
•	Peach
•	Kiwi


Robotic hand/grippers - pre-choice
•	Extension for gripper 2x kitchen ladle, depiction
   ![naberacka-12-1500-28-00](https://cloud.githubusercontent.com/assets/24223167/20757423/7e18a54a-b716-11e6-9f37-7ff1be93120e.jpg)
•	Lynxmotion A Style Gripper Kit w/ Servo
•	Lynxmotion depiction
•	Description, specification, price
•	Alternatives

**Comment by rocboronat** [comment]
@ecnr let me close the issue as it is not something related with this Android app.

Thanks for your time!
