### ISSUE TITLE
Implement fancy Material Design things

### ISSUE THREAD

**Issue by rocboronat** [aeracoop/FloneRemote#6]

**Comment by alorma** [comment]
Any mockup, or design to be applied?

**Comment by rocboronat** [comment]
For the people who asks questions and they remove it later :dancers: , we've mockups but no designs. But, to start, a simple Toolbar with a fancy translucent StatusBar will be something incredible.

By the way, we're going to work with this primary color: #db2027. No idea of the secondary one... we could start with #6393F9. But we're open to Design tips! (i'm daltonic, no joke).

Thanks for asking! :+1:

**Comment by rocboronat** [comment]
Done by @alorma in c22d356f33b098f8a61e54ca385ca3750d627c79
